### PR TITLE
forward frame in waitForReceipt

### PR DESCRIPTION
**Pull request by mpromonet**
Hi,
This pull request allow to get the RECEIPT frame contains using waitForReceipt.
Regards,
Michel.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Many thanks Michael! I have merged it and added your name in contributors :)

Just curious though, why did you need the actual frame in the callback?

**Comment by mpromonet** [comment]
Hi Deepak,
I was investigating several things with STOMP, one of them is to use the RECEIPT frame as answer of SEND, for implementing request-reply.
Best Regards,
Michel.

**Comment by kum-deepak** [comment]
Interesting. :)

There is a standard RPC pattern that can handle generic request reply - even for time taking activities. See an outline for RabbitMQ at https://www.rabbitmq.com/tutorials/tutorial-six-python.html

If this is what you need, there is an initial implementation in the branch rpc. Please check code for the service https://github.com/stomp-js/ng2-stompjs/blob/rpc/src/stomp-rpc.service.ts and the specs https://github.com/stomp-js/ng2-stompjs/blob/rpc/src/specs/app/services/stomp-rpc.service.spec.ts

Currently it is RabbitMQ specific, though extendable to any broker.

In either case please consider to contribute it back - in terms of code or just a HOWTO.

**Comment by mpromonet** [comment]
Thanks, but the mechanism of the temporary queue with the reply-to seems really specific.
Maybe I will try to customize the spring broker to do something similar.

**Pull request merged**
